---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "comm-be.fullname" . }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "comm-be.serviceAccountName" . }}-secret