{{- if .Values.serviceAccountSecret.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "comm-be.serviceAccountName" . }}-secret
  labels:
    {{- include "comm-be.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
